### ISSUE TITLE
Pipeline for GitHub releases

### ISSUE THREAD

**Issue by aartoni** [r-unruh/mtracker#2]
I recently packaged [mtracker for the AUR](https://aur.archlinux.org/packages?K=mtracker) (Arch User Repository), and was wondering if you would be interested in a contribution to enable automatic releases for additional architectures, specifically aarch64 and armv7h.

I was thinking of using [this GitHub workflow](https://github.com/Morganamilo/paru/blob/master/.github/workflows/build.yml) from the `paru` package manager as a starting point.

**Comment by r-unruh** [comment]
Thank you. I will look into it, but it might take a while.

**Comment by aartoni** [comment]
If you don't mind, I'd be happy to help!

**Comment by r-unruh** [comment]
Sure, go ahead.
